### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by cebe** [bedezign/yii2-jsi18n#1]
Hi, thank you for releasing your code. In order for others to be useful the code should be distributed under a license. Otherwise nobody will be allowed to use it. More info on http://choosealicense.com/ or https://tldrlegal.com/.

You can create a license file directly on github by clicking on "Create new file" and name that file "LICENSE", github will provide you with a template.

**Comment by Blizzke** [comment]
[There you go](https://github.com/bedezign/yii2-jsi18n/commit/0e7deed84edb9bcae247130d7761a827ef2dc470).
Thanks for pointing that out.
